from fastapi import APIRouter, HTTPException, Depends, status
from pydantic import BaseModel
from typing import Optional, List, Dict, Any
from app.core.security import get_current_user_payload
from app.db.models import DocumentRepository, SummaryRepository, ChatRepository, SystemLogRepository
from app.services.nlp_engine import generate_summary, answer_rag_question
from app.services.vector_store import chunk_text

router = APIRouter(prefix="/api/ai", tags=["AI Engine"])

class SummarizeRequest(BaseModel):
    doc_id: str
    summary_type: Optional[str] = "abstractive"  # "extractive" or "abstractive"
    length_type: Optional[str] = "medium"        # "short", "medium", "detailed"
    focus_keywords: Optional[List[str]] = None
    language: Optional[str] = "en"

class ChatRequest(BaseModel):
    doc_id: str
    question: str
    language: Optional[str] = "en"

@router.post("/summarize")
def create_summary(req: SummarizeRequest, payload: Dict[str, Any] = Depends(get_current_user_payload)):
    user_id = payload["sub"]
    doc = DocumentRepository.get_by_id(req.doc_id)
    if not doc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")

    if doc["user_id"] != user_id and payload.get("role") != "admin":
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Access denied")

    target_lang = req.language or "en"

    # Generate summary using local NLP engine with Multilingual Support
    result = generate_summary(
        text=doc["extracted_text"],
        summary_type=req.summary_type,
        length_type=req.length_type,
        focus_keywords=req.focus_keywords,
        language=target_lang
    )

    # Save summary to DB
    saved = SummaryRepository.save_summary(
        doc_id=req.doc_id,
        user_id=user_id,
        summary_type=result["summary_type"],
        length_type=result["length_type"],
        executive_summary=result["executive_summary"],
        bullet_points=result["bullet_points"],
        key_takeaways=result["key_takeaways"],
        entities=result["entities"],
        confidence_score=result["confidence_score"],
        compression_ratio=result["compression_ratio"],
        reading_time_saved_min=result["reading_time_saved_min"],
        model_used=result["model_used"],
        language=target_lang
    )

    SystemLogRepository.log_event(
        "INFO", "SUMMARIZATION",
        f"Generated {req.summary_type} ({req.length_type}) summary in {target_lang} for doc {req.doc_id}",
        latency_ms=result["latency_ms"],
        memory_mb=180.0
    )

    return {
        "success": True,
        "summary": saved,
        "metrics": {
            "latency_ms": result["latency_ms"],
            "original_word_count": result["original_word_count"],
            "summary_word_count": result["summary_word_count"],
            "compression_ratio": result["compression_ratio"],
            "reading_time_saved_min": result["reading_time_saved_min"],
            "language": target_lang
        }
    }

@router.get("/documents/{doc_id}/summary")
def get_document_summary(doc_id: str, language: Optional[str] = None, payload: Dict[str, Any] = Depends(get_current_user_payload)):
    user_id = payload["sub"]
    doc = DocumentRepository.get_by_id(doc_id)
    if not doc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")

    target_lang = (language or "en").lower().strip()
    summary = SummaryRepository.get_by_doc_id(doc_id, language=target_lang)
    
    # If a summary in the requested regional language doesn't exist yet OR was generated by the English TextRank fallback, auto-generate in native script!
    needs_generation = not summary or summary.get("language") != target_lang or (target_lang != "en" and summary.get("model_used") == "Local-Hybrid-TextRank")
    if needs_generation:
        result = generate_summary(
            text=doc["extracted_text"],
            summary_type="abstractive",
            length_type="medium",
            language=target_lang
        )
        summary = SummaryRepository.save_summary(
            doc_id=doc_id,
            user_id=user_id,
            summary_type=result["summary_type"],
            length_type=result["length_type"],
            executive_summary=result["executive_summary"],
            bullet_points=result["bullet_points"],
            key_takeaways=result["key_takeaways"],
            entities=result["entities"],
            confidence_score=result["confidence_score"],
            compression_ratio=result["compression_ratio"],
            reading_time_saved_min=result["reading_time_saved_min"],
            model_used=result["model_used"],
            language=target_lang
        )

    return summary

@router.post("/chat")
def chat_with_document(req: ChatRequest, payload: Dict[str, Any] = Depends(get_current_user_payload)):
    user_id = payload["sub"]
    doc = DocumentRepository.get_by_id(req.doc_id)
    if not doc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")

    if not req.question.strip():
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Question cannot be empty")

    # Record User Query
    ChatRepository.add_message(
        doc_id=req.doc_id,
        user_id=user_id,
        sender="user",
        message=req.question.strip()
    )

    # Perform RAG retrieval and Q&A inference with Multilingual Support
    history = ChatRepository.get_doc_messages(req.doc_id)
    ai_response = answer_rag_question(
        doc_id=req.doc_id,
        document_text=doc["extracted_text"],
        question=req.question.strip(),
        history=history,
        language=req.language or "en"
    )

    # Save Assistant Response
    assistant_msg = ChatRepository.add_message(
        doc_id=req.doc_id,
        user_id=user_id,
        sender="assistant",
        message=ai_response["answer"],
        citations=ai_response["citations"],
        confidence_score=ai_response["confidence_score"],
        latency_ms=ai_response["latency_ms"]
    )

    SystemLogRepository.log_event(
        "INFO", "RAG_CHAT",
        f"RAG Q&A query executed for doc {req.doc_id}",
        latency_ms=ai_response["latency_ms"],
        memory_mb=185.0
    )

    return {
        "message": assistant_msg,
        "suggested_questions": ai_response.get("suggested_questions", [])
    }

@router.get("/documents/{doc_id}/chat-history")
def get_chat_history(doc_id: str, payload: Dict[str, Any] = Depends(get_current_user_payload)):
    user_id = payload["sub"]
    doc = DocumentRepository.get_by_id(doc_id)
    if not doc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")

    messages = ChatRepository.get_doc_messages(doc_id)
    return messages

@router.delete("/documents/{doc_id}/chat-history")
def clear_chat_history(doc_id: str, payload: Dict[str, Any] = Depends(get_current_user_payload)):
    user_id = payload["sub"]
    # We can clear messages for this document
    from app.db.database import get_db_connection
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM chat_messages WHERE doc_id = ? AND user_id = ?", (doc_id, user_id))
    conn.commit()
    conn.close()
    return {"success": True, "message": "Conversation history reset"}

@router.get("/process-status/{doc_id}")
def get_process_status(doc_id: str, payload: Dict[str, Any] = Depends(get_current_user_payload)):
    doc = DocumentRepository.get_by_id(doc_id)
    if not doc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")

    chunks = chunk_text(doc["extracted_text"])
    summary = SummaryRepository.get_by_doc_id(doc_id)

    return {
        "doc_id": doc_id,
        "filename": doc["original_name"],
        "status": "ready",
        "steps": [
            {"name": "Document Parsing", "status": "completed", "detail": f"Parsed {doc['page_count']} pages, {doc['word_count']} words"},
            {"name": "Semantic Chunking", "status": "completed", "detail": f"Generated {len(chunks)} overlapping chunks"},
            {"name": "FAISS Vector Indexing", "status": "completed", "detail": "Vector embeddings calculated"},
            {"name": "AI Summarization", "status": "completed" if summary else "ready", "detail": f"{summary['summary_type'].capitalize()} summary available" if summary else "Click Generate to summarize"}
        ],
        "chunks_count": len(chunks),
        "has_summary": summary is not None
    }

LANGUAGE_FULL_NAMES = {
    "te": "Telugu (తెలుగు)",
    "hi": "Hindi (हिन्दी)",
    "ta": "Tamil (தமிழ்)",
    "kn": "Kannada (ಕನ್ನಡ)",
    "ml": "Malayalam (മലയാളം)",
    "mr": "Marathi (मराठी)",
    "bn": "Bengali (বাংলা)",
    "gu": "Gujarati (ગુજરાતી)",
    "es": "Spanish (Español)",
    "fr": "French (Français)",
    "de": "German (Deutsch)",
    "en": "English"
}

@router.get("/tts")
def text_to_speech(text: str, lang: str = "en"):
    """
    High-fidelity Neural Multilingual Text-to-Speech audio streaming endpoint.
    If the text is in English and the user requested Telugu, Hindi, Tamil, etc.,
    it automatically translates the text into pure native script first,
    and then synthesizes 100% natural, fluent native speech audio.
    """
    import urllib.parse
    import requests
    import re
    from fastapi.responses import Response
    from app.services.nlp_engine import call_groq_llm, call_gemini_llm

    clean_text = text.strip()[:800]
    if not clean_text:
        raise HTTPException(status_code=400, detail="Text content required for speech synthesis")

    lang_code = lang.lower().split("-")[0]
    spoken_text = clean_text

    # Script Detection: If the user chose an Indic or Foreign language but the text is in English,
    # translate it to fluent native script before speaking so it never reads garbled letters.
    if lang_code != "en" and not re.search(r'[\u0900-\u0D7F]', clean_text):
        target_name = LANGUAGE_FULL_NAMES.get(lang_code, lang_code)
        messages = [
            {
                "role": "system",
                "content": f"You are an expert native {target_name} translator. Translate the given text into pure, fluent, natural {target_name} script. Output ONLY the translated text without explanations, greetings, or English words."
            },
            {
                "role": "user",
                "content": clean_text
            }
        ]
        try:
            res = call_groq_llm(messages, max_tokens=600)
            if not res:
                res = call_gemini_llm(messages, max_tokens=600)
            if res and res[0].strip():
                spoken_text = res[0].strip()
        except Exception:
            pass

    tts_url = f"https://translate.google.com/translate_tts?ie=UTF-8&q={urllib.parse.quote(spoken_text)}&tl={lang_code}&client=tw-ob"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    }

    try:
        res = requests.get(tts_url, headers=headers, timeout=12)
        if res.status_code == 200 and len(res.content) > 50:
            return Response(
                content=res.content,
                media_type="audio/mpeg",
                headers={"Cache-Control": "public, max-age=86400"}
            )
    except Exception:
        pass

    raise HTTPException(status_code=500, detail="Speech audio synthesis unavailable")
